[dbs.main-master]
host            = "127.0.0.1"
port            = 3306
user            = "root"
password        = "***"
charset         = "utf8mb4"
database        = "gosports"
debug           = true

[works]
match_url             = "https://live.leisu.com/saicheng?date=20190703"
match_interval        = 10
team_url              = "https://live.leisu.com/wanchang?date=20190702"
team_interval         = 15
