[dbs.main-master]
host            = "127.0.0.1"
port            = 3306
user            = "root"
password        = "***"
charset         = "utf8mb4"
database        = "gosports"
debug           = true

[works]
match_url             = "https://live.leisu.com/%s?date=%s"
match_interval        = 3600
match_day_range       = 3
team_url              = "https://live.leisu.com/wanchang?date=%s"
team_interval         = 3600
