[dbs.main-master]
host            = "127.0.0.1"
port            = 3306
user            = "root"
password        = "cp2290812"
charset         = "utf8mb4"
database        = "gosports"
debug           = true
