[env]
debug       = true
host        = "127.0.0.1"
port        = 1080
ips         = ["127.0.0.1", "127.0.0.2", "127.0.0.3"]
ids         = [1, 2, 3]

[dbs.master]
host        = "127.0.0.1"
port        = 3306

[dbs.slave]
host        = "127.0.0.1"
port        = 3306

[log]
log_filename            = "./logs/gateway/gateway.log"
log_file_maxsize        = 100
log_time_key            = "Time"
log_level_key           = "Level"
log_name_key            = "Logger"
log_caller_key          = "Caller"
log_message_key         = "Message"
stacktrace_key          = "Stracktrace"
log_level               = "Debug"
stacktrace_level        = "Error"
service_name            = "gateway"