[env]
debug       = true
host        = "127.0.0.1"
port        = 1080
ips         = ["127.0.0.1", "127.0.0.2", "127.0.0.3"]
ids         = [1, 2, 3]

[dbs.master]
host        = "127.0.0.1"
port        = 3306

[dbs.slave]
host        = "127.0.0.1"
port        = 3306

[[fruit]]
  name = "apple"

  [fruit.physical]
    color = "red"
    shape = "round"

  [[fruit.variety]]
    name = "red delicious"

  [[fruite.variety]]

  [[fruit.variety]]
    name = "granny smith"

[[fruit]]
  name = "banana"

  [[fruit.variety]]
    name = "plantain"